#!/bin/bash
CONFIG_FILE="/etc/ok.conf"
DATE=`date +%Y-%m-%d`
. $CONFIG_FILE

VIDEO="$TMP/$DATE.avi"
LIST="$TMP/stills.list"

sudo raspistill -o $TMP/tl_%04d.jpg -tl $SLEEP -t $TIME --nopreview --exposure $EXPOSURE --awb $AWB

ls $TMP/tl_*.jpg > $LIST

mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:aspect=16/9:vbitrate=8000000 -vf scale=1920:1080 -o $VIDEO -mf type=jpeg:fps=24 mf://@$LIST

sudo rm $TMP/tl_*.jpg $LIST

URL=`youtube-upload --email=$USER --password=$PASS --title=$TITLE --description=$DESC --category=$CATE --keywords=$KEYW$VIDEO`
twitter set "$TWEET$URL"

rm $VIDEO
