#!/bin/bash
CONFIG_FILE="/etc/ok.conf"
DATE=`date +%Y-%m-%d`
. $CONFIG_FILE

VIDEO="$TMP/$DATE.avi"
LIST="$TMP/stills.list"

sudo raspistill -o $TMP/tl_%04d.jpg -tl $SLEEP -t $TIME --nopreview --exposure $EXPOSURE --awb $AWB

ls $TMP/tl_*.jpg > $LIST

mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:aspect=16/9:vbitrate=8000000 -vf scale=1920:1080 -o $VIDEO -mf type=jpeg:fps=24 mf://@$LIST
#mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:aspect=16/9:vbitrate=8000000 -vf scale=1920:1080 -o $FILE -mf type=jpeg:fps=24 mf://@$TMP/stills.list
#mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:aspect=16/9:vbitrate=8000000 -vf scale=1920:1080 -o $FILE -mf type=jpeg:fps=24 mf://@$TMP/stills.list
#mencoder -ovc lavc -lavcopts vcodec=mpeg4:vpass=1:vbitrate=1620000:mbd=2:keyint=132:v4mv:vqmin=3:vlelim=-4:vcelim=7:lumi_mask=0.07:dark_mask=0.10:naq:vqcomp=0.7:vqblur=0.2:mpeg_quant -mf type=sgi:fps=25 -nosound -o /dev/null $FILE


sudo rm $TMP/tl_*.jpg $LIST

URL=`youtube-upload --email=$USER --password=$PASS --title=$TITLE --description=$DESC --category=$CATE --keywords=$KEYW$VIDEO`
twitter set "$TWEET$URL"

rm $VIDEO
