#!/bin/sh
$TMP="/var/cache/overkill"

#TODO
#test mencoder
#test twitter

sudo mkdir -p $TMP/timelapse
sudo mkdir -p $TMP/rht03

if [[ ! -f /etc/ok.conf ]]; then
  sudo cp ok.conf.sample /etc/ok.conf
  sudo chown root:root /etc/ok.conf
  echo "Configure: /etc/ok.conf"
  echo "Warning: /etc/ok.conf will be readable by everyone - you share you Pi?!?"
fi

echo "Compiling rht03"
cd rht03
make rht03
cp rht03 ../ok-rht03
cd ..

echo "Copy to /usr/local/bin"
sudo cp ok-* /usr/local/bin/
